# Generated by Django 5.1.6 on 2026-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='card_label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
