from django.urls import path

from .credit_card_views import (
    credit_card_cards,
    credit_card_categories,
    credit_card_dashboard,
    credit_card_transactions_collection,
    delete_credit_card,
    delete_credit_card_transaction,
    delete_many_credit_card_transactions,
    rename_credit_card,
    set_credit_card_transaction_hidden,
    set_many_credit_card_transactions_hidden,
)
from .holdings_views import (
    accounts_dashboard,
    holdings_collection,
    holdings_item,
    market_data_quote,
    refresh_holdings_market_values,
    upsert_cash_account,
)
from .import_views import (
    commit_batch_endpoint,
    commit_import_review,
    create_import_review,
    download_template,
    export_all_data,
    export_credit_cards,
    export_fhsa,
    export_holdings,
    export_net_worth,
    export_rrsp,
    export_tfsa,
    export_transactions,
    get_import_review,
    import_full_backup,
    import_review_row_item,
    import_holdings_csv,
    import_rogers_credit_csv,
)
from .net_worth_views import net_worth_collection, net_worth_item
from .rrsp_views import (
    rrsp_account_item,
    rrsp_accounts,
    rrsp_annual_limit_item,
    rrsp_annual_limits,
    rrsp_contributions,
    rrsp_import_csv,
    rrsp_opening_balance,
    rrsp_reset,
    rrsp_summary,
    rrsp_transaction_item,
    rrsp_transactions,
    rrsp_transfers,
)
from .settings_views import settings_features
from .tfsa_views import (
    tfsa_account_item,
    tfsa_accounts,
    tfsa_annual_limit_item,
    tfsa_annual_limits,
    tfsa_contributions,
    tfsa_import_csv,
    tfsa_opening_balance,
    tfsa_reset,
    tfsa_summary,
    tfsa_transaction_item,
    tfsa_transactions,
    tfsa_transfers,
)
from .fhsa_views import (
    fhsa_account_item,
    fhsa_accounts,
    fhsa_contributions,
    fhsa_import_csv,
    fhsa_opening_balance,
    fhsa_opening_balance_base_year,
    fhsa_reset,
    fhsa_summary,
    fhsa_transaction_item,
    fhsa_transactions,
    fhsa_transfers,
)
from .transaction_views import (
    delete_many_transactions,
    get_ledger,
    list_securities,
    list_transaction_types,
    transactions_collection,
    transactions_item,
)
from .views import (
    acb_page,
    credit_card_page,
    fhsa_page,
    health_view,
    holdings_page,
    import_page,
    index_page,
    login_page,
    net_worth_page,
    rrsp_page,
    security_page,
    tfsa_page,
)

urlpatterns = [
    path("login", login_page, name="login"),
    path("", index_page, name="index"),
    path("security/<str:security>", security_page, name="security"),
    path("acb", acb_page, name="acb"),
    path("credit-card", credit_card_page, name="credit-card"),
    path("net-worth", net_worth_page, name="net-worth"),
    path("tfsa", tfsa_page, name="tfsa"),
    path("rrsp", rrsp_page, name="rrsp"),
    path("fhsa", fhsa_page, name="fhsa"),
    path("import", import_page, name="import"),
    path("holdings", holdings_page, name="holdings"),
    path("__django__/health/", health_view, name="django-health"),
    path("api/transactions", transactions_collection, name="transactions-collection"),
    path("api/transactions/<int:transaction_id>", transactions_item, name="transactions-item"),
    path("api/transactions/delete-many", delete_many_transactions, name="transactions-delete-many"),
    path("api/ledger", get_ledger, name="ledger"),
    path("api/securities", list_securities, name="securities"),
    path("api/transaction-types", list_transaction_types, name="transaction-types"),
    path("api/accounts/dashboard", accounts_dashboard, name="accounts-dashboard"),
    path("api/accounts/cash", upsert_cash_account, name="accounts-cash"),
    path("api/holdings", holdings_collection, name="holdings-collection"),
    path("api/holdings/<int:holding_id>", holdings_item, name="holdings-item"),
    path("api/market-data/quote", market_data_quote, name="market-data-quote"),
    path("api/holdings/refresh-market-values", refresh_holdings_market_values, name="holdings-refresh-market-values"),
    path("api/import/holdings-csv", import_holdings_csv, name="import-holdings-csv"),
    path("api/import/credit-card/rogers-csv", import_rogers_credit_csv, name="import-credit-card-rogers-csv"),
    path("api/import/review", create_import_review, name="import-review-create"),
    path("api/import/review/<int:batch_id>", get_import_review, name="import-review-get"),
    path("api/import/review/<int:batch_id>/rows/<int:row_id>", import_review_row_item, name="import-review-row-item"),
    path("api/import/review/<int:batch_id>/commit", commit_import_review, name="import-review-commit"),
    path("api/import/commit/<int:batch_id>", commit_batch_endpoint, name="import-commit-alias"),
    path("api/import/template/<str:template_type>", download_template, name="import-template"),
    path("api/export/transactions", export_transactions, name="export-transactions"),
    path("api/export/holdings", export_holdings, name="export-holdings"),
    path("api/export/net-worth", export_net_worth, name="export-net-worth"),
    path("api/export/credit-cards", export_credit_cards, name="export-credit-cards"),
    path("api/export/tfsa", export_tfsa, name="export-tfsa"),
    path("api/export/rrsp", export_rrsp, name="export-rrsp"),
    path("api/export/fhsa", export_fhsa, name="export-fhsa"),
    path("api/export/all", export_all_data, name="export-all-data"),
    path("api/import/full-backup", import_full_backup, name="import-full-backup"),
    path("api/net-worth", net_worth_collection, name="net-worth-collection"),
    path("api/net-worth/<int:entry_id>", net_worth_item, name="net-worth-item"),
    path("api/settings/features", settings_features, name="settings-features"),
    path("api/credit-card/dashboard", credit_card_dashboard, name="credit-card-dashboard"),
    path("api/credit-card/cards", credit_card_cards, name="credit-card-cards"),
    path("api/credit-card/cards/<str:card_label>/rename", rename_credit_card, name="credit-card-rename"),
    path("api/credit-card/cards/<str:card_label>", delete_credit_card, name="credit-card-delete"),
    path("api/credit-card/categories", credit_card_categories, name="credit-card-categories"),
    path("api/credit-card/transactions", credit_card_transactions_collection, name="credit-card-transactions-collection"),
    path("api/credit-card/transactions/<int:transaction_id>/hidden", set_credit_card_transaction_hidden, name="credit-card-transaction-hidden"),
    path("api/credit-card/transactions/hide-many", set_many_credit_card_transactions_hidden, name="credit-card-transactions-hide-many"),
    path("api/credit-card/transactions/<int:transaction_id>", delete_credit_card_transaction, name="credit-card-transaction-delete"),
    path("api/credit-card/transactions/delete-many", delete_many_credit_card_transactions, name="credit-card-transactions-delete-many"),
    path("api/tfsa/summary", tfsa_summary, name="tfsa-summary"),
    path("api/tfsa/accounts", tfsa_accounts, name="tfsa-accounts"),
    path("api/tfsa/accounts/<int:account_id>", tfsa_account_item, name="tfsa-account-item"),
    path("api/tfsa/opening-balance", tfsa_opening_balance, name="tfsa-opening-balance"),
    path("api/tfsa/annual-limits", tfsa_annual_limits, name="tfsa-annual-limits"),
    path("api/tfsa/annual-limits/<int:year>", tfsa_annual_limit_item, name="tfsa-annual-limit-item"),
    path("api/tfsa/transactions", tfsa_transactions, name="tfsa-transactions"),
    path("api/tfsa/transactions/<int:transaction_id>", tfsa_transaction_item, name="tfsa-transaction-item"),
    path("api/tfsa/contributions", tfsa_contributions, name="tfsa-contributions"),
    path("api/tfsa/transfers", tfsa_transfers, name="tfsa-transfers"),
    path("api/tfsa/reset", tfsa_reset, name="tfsa-reset"),
    path("api/tfsa/import-csv", tfsa_import_csv, name="tfsa-import-csv"),
    path("api/rrsp/summary", rrsp_summary, name="rrsp-summary"),
    path("api/rrsp/accounts", rrsp_accounts, name="rrsp-accounts"),
    path("api/rrsp/accounts/<int:account_id>", rrsp_account_item, name="rrsp-account-item"),
    path("api/rrsp/opening-balance", rrsp_opening_balance, name="rrsp-opening-balance"),
    path("api/rrsp/annual-limits", rrsp_annual_limits, name="rrsp-annual-limits"),
    path("api/rrsp/annual-limits/<int:year>", rrsp_annual_limit_item, name="rrsp-annual-limit-item"),
    path("api/rrsp/transactions", rrsp_transactions, name="rrsp-transactions"),
    path("api/rrsp/transactions/<int:transaction_id>", rrsp_transaction_item, name="rrsp-transaction-item"),
    path("api/rrsp/contributions", rrsp_contributions, name="rrsp-contributions"),
    path("api/rrsp/transfers", rrsp_transfers, name="rrsp-transfers"),
    path("api/rrsp/reset", rrsp_reset, name="rrsp-reset"),
    path("api/rrsp/import-csv", rrsp_import_csv, name="rrsp-import-csv"),
    path("api/fhsa/summary", fhsa_summary, name="fhsa-summary"),
    path("api/fhsa/accounts", fhsa_accounts, name="fhsa-accounts"),
    path("api/fhsa/accounts/<int:account_id>", fhsa_account_item, name="fhsa-account-item"),
    path("api/fhsa/opening-balance", fhsa_opening_balance, name="fhsa-opening-balance"),
    path("api/fhsa/opening-balance-base-year", fhsa_opening_balance_base_year, name="fhsa-opening-balance-base-year"),
    path("api/fhsa/transactions", fhsa_transactions, name="fhsa-transactions"),
    path("api/fhsa/transactions/<int:transaction_id>", fhsa_transaction_item, name="fhsa-transaction-item"),
    path("api/fhsa/contributions", fhsa_contributions, name="fhsa-contributions"),
    path("api/fhsa/transfers", fhsa_transfers, name="fhsa-transfers"),
    path("api/fhsa/reset", fhsa_reset, name="fhsa-reset"),
    path("api/fhsa/import-csv", fhsa_import_csv, name="fhsa-import-csv"),
]
