# Generated by Django 5.1.6 on 2026-03-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FhsaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhsa_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=64)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='staged', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RrspAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrsp_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TfsaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfsa_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='app_settings_user_key_pk')],
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('transaction_date', models.DateField()),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(default='', max_length=128)),
                ('activity_type', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=8, null=True)),
                ('merchant_category', models.CharField(blank=True, max_length=128, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_city', models.CharField(blank=True, max_length=128, null=True)),
                ('merchant_region', models.CharField(blank=True, max_length=128, null=True)),
                ('merchant_country', models.CharField(blank=True, max_length=128, null=True)),
                ('merchant_postal', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('rewards', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'transaction_date', 'id'], name='idx_cc_provider_date'), models.Index(fields=['provider', 'merchant_category'], name='idx_cc_provider_category')],
            },
        ),
        migrations.CreateModel(
            name='FhsaContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('contribution_type', models.CharField(max_length=64)),
                ('is_qualifying_withdrawal', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fhsa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.fhsaaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhsa_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contribution_date', 'id'], name='idx_fhsa_contributions_date')],
            },
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=128, null=True)),
                ('account_classification', models.CharField(blank=True, max_length=128, null=True)),
                ('account_number', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(blank=True, max_length=32, null=True)),
                ('mic', models.CharField(blank=True, max_length=16, null=True)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('security_type', models.CharField(blank=True, max_length=128, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_price_currency', models.CharField(blank=True, max_length=8, null=True)),
                ('book_value_cad', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('market_value_currency', models.CharField(blank=True, max_length=8, null=True)),
                ('unrealized_return', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['as_of', 'account_number', 'symbol'], name='idx_holdings_as_of_account')],
                'constraints': [models.UniqueConstraint(fields=('user', 'as_of', 'account_number', 'symbol'), name='holdings_unique_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_order', models.IntegerField()),
                ('security', models.CharField(max_length=32)),
                ('trade_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shares', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('amount_per_share', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('commission', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('source', models.CharField(default='import_review', max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.importbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'row_order', 'id'], name='idx_import_batch_rows_batch')],
            },
        ),
        migrations.CreateModel(
            name='NetWorthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entry_date'], name='idx_net_worth_entry_date')],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_date'), name='networth_user_date_unique')],
            },
        ),
        migrations.CreateModel(
            name='RrspAnnualLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('annual_limit', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrsp_annual_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='rrsp_user_year_unique')],
            },
        ),
        migrations.CreateModel(
            name='RrspContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('contribution_type', models.CharField(max_length=64)),
                ('is_unused', models.BooleanField(default=False)),
                ('deducted_tax_year', models.IntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rrsp_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.rrspaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrsp_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contribution_date', 'id'], name='idx_rrsp_contributions_date')],
            },
        ),
        migrations.CreateModel(
            name='TfsaAnnualLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('annual_limit', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfsa_annual_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='tfsa_user_year_unique')],
            },
        ),
        migrations.CreateModel(
            name='TfsaContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('contribution_type', models.CharField(max_length=64)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tfsa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.tfsaaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfsa_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contribution_date', 'id'], name='idx_tfsa_contributions_date')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(max_length=32)),
                ('trade_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('shares', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('amount_per_share', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('commission', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('memo', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['security', 'trade_date', 'id'], name='idx_transactions_security_date')],
            },
        ),
    ]
